module.exports = {
  USER_EMAIL_EXISTS: "Email already Registered.",
  USER_EMAIL_NOT_EXISTS: "Email Does Not Exist",
  USER_EMAIL_REGISTERED: "User Registered Successfully",
  USER_SIGNUP_ERROR: "Error in Registration",
  SUCCESS_RESETPASS: "Password Successfully Updated",
  NOT_MATCH_OLDPASSWORD: "Old Password is Wrong",
  SUCCESS_INSERT: "Record Sucessfully Inserted.",
  SUCCESS_UPDATE: "Record Sucessfully Updated.",
  SUCCESS_DELETE: "Record Sucessfully Deleted.",
  SUCCESS_ACTIVE: "Record Sucessfully Activated.",
  INVALID_UPDATE_DATA: "invalid Update data",
  SUCCESS_MSG: "Successfully Data Fetch",
  Cart_PRODUCT_EXISTS: "Product Added inside Cart.",
  SUCCESS_INSERT: "Record Sucessfully Inserted.",
  SUCCESS_UPDATE: "Record Sucessfully Updated.",
  SUCCESS_DELETE: "Record Sucessfully Deleted.",

  0: "Pending",
  1: "Accept",
  2: "Reject",
  3: "Cancel",
  4: "dispatch",
  5: "success",
};
